# Service Parameters
yolo_service:
  ros__parameters:
    version: 'yolov7'
    choice: 'real'
    camera_name: 'oak'
    deepsort: False

# RGBD Parameters
yolo_client:
  ros__parameters:
    choice: 'real'
    camera_name: 'oak'
    deepsort_service: True
    debug: False

# Make sure to match the choice and camera_name values, deepsort_service is True only for Yolo V7
