# Service Parameters
service:
  ros__parameters:
    choice: 'real'
    camera_name: 'realsense'
    deepsort: False
    version: 'yolov8'


# Client Parameters
client:
  ros__parameters:
    version: 'yolov8'

# Make sure to match the version values